set -g status-style bg=default,fg={{colors.tertiary.default.hex}}
set -g status-right "#[fg={{colors.primary.default.hex}},bold,underscore]#S#[fg={{colors.tertiary.default.hex}},nounderscore]  %H:%M"
set -g window-status-current-style "#{?window_zoomed_flag,fg={{colors.tertiary.default.hex}},fg={{colors.primary.default.hex}},bold,underscore}"
