-- local modes = {
--   ["n"] = "NORMAL",
--   ["no"] = "NORMAL",
--   ["v"] = "VISUAL",
--   ["V"] = "VISUAL LINE",
--   [""] = "VISUAL BLOCK",
--   ["s"] = "SELECT",
--   ["S"] = "SELECT LINE",
--   [""] = "SELECT BLOCK",
--   ["i"] = "INSERT",
--   ["ic"] = "INSERT",
--   ["R"] = "REPLACE",
--   ["Rv"] = "VISUAL REPLACE",
--   ["c"] = "COMMAND",
--   ["cv"] = "VIM EX",
--   ["ce"] = "EX",
--   ["r"] = "PROMPT",
--   ["rm"] = "MOAR",
--   ["r?"] = "CONFIRM",
--   ["!"] = "SHELL",
--   ["t"] = "TERMINAL",
-- }
--
-- local function get_mode()
-- 	local current_mode = vim.api.nvim_get_mode().mode
-- 	return string.format(" %s ", modes[current_mode]:upper())
-- end
--
-- Statusline = {}
--
-- vim.o.statusline = "%#BlinkCmpMenuBorder# 󰥓%r %=%=%f %=%(%#Insert# %l/%L%) %k "
-- vim.o.cmdheight = 0
