monitor=,highres@highrr,0x0, 1.33333333

# exec-once = waybar & swww-daemon
exec-once = waybar
exec-once = wl-paste -t text -w cliphist store
exec-once = wl-paste -t image -w cliphist store
exec-once = hypridle & hyprpaper

source = ./keymaps.conf
source = ./variables.conf
source = ./animations.conf
source = ./windowrules.conf

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = NVD_BACKEND,direct
