set -g status-style bg=default,fg=#d1bfe7
set -g status-right "#[fg=#98ccf9,bold,underscore]#S#[fg=#d1bfe7,nounderscore]  %H:%M"
set -g window-status-current-style "#{?window_zoomed_flag,fg=#d1bfe7,fg=#98ccf9,bold,underscore}"
