[manager]
cwd = { fg = "#e6e0e9" }

# Tab
tab_active = { fg = "#36265d", bg = "#d0bcfe", bold = true }
tab_inactive = { fg = "#e9ddff", bg = "#210f47" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff7394", bg = "#ff7394" }
marker_cut = { fg = "#ffd9e2", bg = "#ffd9e2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#efb8c7", bg = "#efb8c7" }

# Count
count_copied = { fg = "#31101d", bg = "#ffd9e2" }
count_cut = { fg = "#31101d", bg = "#ffd9e2" }
count_selected = { fg = "#36265d", bg = "#efb8c7" }

# Border
border_symbol = "│"
border_style  = { fg = "#d0bcfe" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#36265d", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#d0bcfe", fg = "#36265d", bold = true }
normal_alt  = { bg = "#49454e", fg = "#cac4cf" }

# Select mode
select_main = { bg = "#ccc2db", fg = "#332d41", bold = true }
select_alt  = { bg = "#49454e", fg = "#cac4cf" }

# Unset mode
unset_main = { bg = "#efb8c7", fg = "#4a2532", bold = true }
unset_alt  = { bg = "#49454e", fg = "#cac4cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d0bcfe", bg = "#3b383e" }
progress_error = { fg = "#ffb4ab", bg = "#3b383e" }

# Permissions
permissions_t = { fg = "#7c62a2" }
permissions_w = { fg = "#d33b65" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff406d" }
permissions_s = { fg = "#8644ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d0bcfe" }
active = { fg = "#efb8c7", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#d0bcfe" }
value = { fg = "#e6e0e9" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#d0bcfe", bg = "#36265d" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d0bcfe" }
title = {}
hovered = { fg = "#ffd9e2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3b383e" }
cand = { fg = "#d0bcfe" }
rest = { fg = "#36265d" }
desc = { fg = "#e6e0e9" }
separator = " ▶ "
separator_style = { fg = "#e6e0e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e6e0e9" }
run = { fg = "#e6e0e9" }
footer = { fg = "#332d41", bg = "#ccc2db" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#efb8c7" }
title_warn = { fg = "#d0bcfe" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e6e0e9" },
    { name = "*/", fg = "#d0bcfe" },
]

# : ]]]
