set -g status-style bg=default,fg=#ecb8ce
set -g status-right "#[fg=#c7bfff,bold,underscore]#S#[fg=#ecb8ce,nounderscore]  %H:%M"
set -g window-status-current-style "#{?window_zoomed_flag,fg=#ecb8ce,fg=#c7bfff,bold,underscore}"
