set -g status-style bg=default,fg=#a0cfd4
set -g status-right "#[fg=#a1d39a,bold,underscore]#S#[fg=#a0cfd4,nounderscore]  %H:%M"
set -g window-status-current-style "#{?window_zoomed_flag,fg=#a0cfd4,fg=#a1d39a,bold,underscore}"
