set -g status-style bg=default,fg=#a1ced5
set -g status-right "#[fg=#9ed49d,bold,underscore]#S#[fg=#a1ced5,nounderscore]  %H:%M"
set -g window-status-current-style "#{?window_zoomed_flag,fg=#a1ced5,fg=#9ed49d,bold,underscore}"
