bind ` source-file ~/.config/tmux/tmux.conf
source-file ~/.config/tmux/theme.conf
set -g prefix M-Space

set -g base-index 1
set -g pane-base-index 1
# set -g status-style bg=default,fg=white,bright
set -g status-position top
set -g status-left ""
# set -g status-right "#[fg=magenta,bold,underscore]#S#[fg=white,bright,nounderscore]  %H:%M"
set -g window-status-format "#I.#W "
set -g window-status-current-format "󰥓 #W "
# set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,bold,underscore}"
set -g renumber-windows on
set -g mouse on
set -g escape-time 0
set -g repeat-time 1000
set -g history-limit 10000

set -g default-terminal "tmux-256color"

# Window Modal
bind w switch-client -T w-modal
bind -T w-modal n display-popup -w 90% -h 90%
bind -T w-modal w choose-tree -Zw
bind -T w-modal s split-window -v
bind -T w-modal v split-window -h
bind -T w-modal h select-pane -L
bind -T w-modal j select-pane -D
bind -T w-modal k select-pane -U
bind -T w-modal l select-pane -R
bind -T w-modal C-h resize-pane -L 5
bind -T w-modal C-j resize-pane -D 5
bind -T w-modal C-k resize-pane -U 5
bind -T w-modal C-l resize-pane -R 5
bind -T w-modal r command-prompt {rename-window '%%'}

bind f command-prompt {find-window -i '%%'}
bind k last-window
bind l next-window
bind h previous-window
bind n new-window -a
bind c new-window -a -c "#{pane_current_path}"
