bind ` source-file ~/.config/tmux/tmux.conf
unbind C-b
set -g prefix M-Space

set -g base-index 1
set -g pane-base-index 1
set -g status-style bg=default,fg=black,bright
set -g status-position top
set -g status-left ""
set -g status-right "#[fg=magenta,bold,underscore]#S#[fg=black,bright,nounderscore]  %H:%M"
set -g window-status-format "#I.#W"
set -g window-status-current-format "󰥓#W"
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,bold,underscore}"
set -g renumber-windows on
set -g mouse on
set -g escape-time 0
set -g repeat-time 1000
set -g history-limit 10000

set -g default-terminal "tmux-256color"

# Mode: Pane Selection
bind w switch-client -T pane-selection
bind -T pane-selection w choose-tree -Zw
bind -T pane-selection s split-window -v
bind -T pane-selection v split-window -h
bind -T pane-selection h select-pane -L
bind -T pane-selection j select-pane -D
bind -T pane-selection k select-pane -U
bind -T pane-selection l select-pane -R
bind -T pane-selection C-h resize-pane -L 5
bind -T pane-selection C-j resize-pane -D 5
bind -T pane-selection C-k resize-pane -U 5
bind -T pane-selection C-l resize-pane -R 5

bind l next-window
bind h previous-window
bind n new-window
