vim.o.swapfile = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.clipboard = "unnamedplus"
vim.o.tabstop = 6
vim.o.shiftwidth = 6
vim.o.showmode = false
vim.o.scrolloff = 10
vim.o.mouse = "nvichar"
vim.o.list = true
vim.o.incsearch = true
vim.o.inccommand = "split"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.confirm = true
vim.o.copyindent = true
vim.o.breakindent = true
vim.o.showbreak = "󱞩 "
vim.o.smartindent = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.startofline = true
vim.o.undofile = true
vim.o.wrapmargin = 5
vim.o.laststatus = 3
vim.o.cmdheight = 1
vim.o.winborder = "rounded"
vim.o.listchars = "tab:  ,trail:"
vim.o.cursorline = false
vim.o.termguicolors = true
-- o.guicursor =
-- 	"n:block-MiniStatusLineModeNormal,i:block-MiniStatusLineModeInsert,v:block-MiniStatusLineModeVisual,r:block-MiniStatusLineModeReplace,t:block-MiniStatusLineModeOther"
